### ISSUE TITLE
Why a Threshold is needed for DoG algorithm?

### ISSUE THREAD

**Issue by ghost** [alexpeattie/xdog-sketch#1]
Firstly, Thank you for sharing this excellent  project!

When turning off the "XDoG mode" switch, DoG algorithm is used.
From the [doc](https://docs.gimp.org/2.6/en/plug-in-dog.html), it seems that the DoG algorithm **only needs two parameters(sigma-1 & sigma-2)**. **So I'm confused why a "Threshold" is needed for DoG algorithm?**

I can't fully understand the following line, due to I'm not very familar with the library function:
https://github.com/alexpeattie/xdog-sketch/blob/b19831e856475fb728d2f0a02fee7fe7f98d0024/src/xdog.js#L50

Why `relativeDiff` needs to be subtracted by the Threshold? i.e.**Why not simply invert color to directly get the line drawing?**

If convenient, could you answer this question? Thanks in advance.

**Comment by alexpeattie** [comment]
Hey @gceboh good question. The unthresholded DoG image isn't black and white, but is a grey image with the edges enhanced (DoG/LoG was traditionally used for edge detection for computer vision applications) like this:

![image](https://user-images.githubusercontent.com/636814/93754863-48ccd280-fbfa-11ea-94e6-a6a99da95280.png)

The thresholding just makes it black and white, as below:

![image](https://user-images.githubusercontent.com/636814/93755245-db6d7180-fbfa-11ea-9c85-0cf1d6b1e02a.png)


As you can probably tell from playing with the demo, adjusting the threshold variable determines which gray values get sent to black and which get sent to white. Hope that makes sense! If you want to learn more, I'd recommend [Winnemoller et al.'s paper](https://www.kyprianidis.com/p/cag2012/winnemoeller-cag2012.pdf) which gives great background on the (thresholded) DoG algorithm.

**Comment by ghost** [comment]
Thank you very much for the detailed explanation!
(By the way, this project and corresponding online demo had been added to [Awesome-Edge-Detection-Papers](https://github.com/MarkMoHR/Awesome-Edge-Detection-Papers). Thank again for this high quality implementation! )
